# Generated by Django 5.2.14 on 2026-06-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='weak_topics',
            field=models.TextField(blank=True, default=''),
        ),
    ]
