# Generated by Django 5.2.14 on 2026-06-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_studentprofile_weak_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='resource_type',
            field=models.CharField(choices=[('video', 'VideoResource'), ('text', 'TextResource'), ('code', 'CodeResource')], default='text', max_length=10),
        ),
    ]
