# Generated by Django 5.2.14 on 2026-06-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_learningobject_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'Documento / Conferencia'), ('AUDIO', 'Audio / Podcast'), ('VIDEO', 'Tutorial / Video'), ('EJERCICIO', 'Práctica / Ejercicio Práctico')], default='text', max_length=10),
        ),
    ]
