# Generated by Django 5.2.14 on 2026-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_alter_learningobject_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'Documento / Conferencia'), ('AUDIO', 'Audio / Podcast'), ('VIDEO', 'Tutorial / Video'), ('EJERCICIO', 'Práctica / Ejercicio Práctico')], default='PDF', max_length=10),
        ),
    ]
