# Generated by Django 5.2.14 on 2026-06-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_learningobject_file_learningobject_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='learningobject',
            name='topic',
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'Documento / Conferencia'), ('AUDIO', 'Audio / Podcast'), ('VIDEO', 'Tutorial / Video'), ('EJERCICIO', 'Práctica / Ejercicio Práctico'), ('EXAMEN', 'Examen de Años Anteriores')], default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='topics',
            field=models.ManyToManyField(related_name='learning_objects', to='recommendation.topic'),
        ),
    ]
